spring:
  application:
    name: mab-request
  servlet:
    multipart:
      max-file-size: 1000MB   # Set your desired maximum file size here
      max-request-size: 1000MB  # Set the maximum request size here if needed
  rabbitmq:
    host: 192.241.149.226
    port: 5672
    username: admin
    password: lEtfbOBZDtAg4v7
    virtual-host: "/"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:lEtfbOBZDtAg4v7}
    url: ${DB_URL:jdbc:postgresql://192.241.149.226:5432/db_mab}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://192.241.149.226:8080/realms/mab-manitos
          jwk-set-uri: http://192.241.149.226:8080/realms/mab-manitos/protocol/openid-connect/certs
server:
  port: 8012
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
token:
  converter:
    principal-attribute: preferred_username
    resource-id: backend_security_test

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.241.149.226:9411/api/v2/spans

security-constraints:
  - auth-roles:
      - doctor
      - doctorJefe
    security-collections:
      - name: prueba
        patterns:
          - /api/v1/request
        methods:
          - GET
          - POST
          - PUT
          - DELETE