spring:
  application:
    name: mab-request
  servlet:
    multipart:
      max-file-size: 1000MB   # Set your desired maximum file size here
      max-request-size: 1000MB  # Set the maximum request size here if needed
  rabbitmq:
    host: ${RABBITMQ_HOST:192.241.149.226}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_SECRET_KEY:lEtfbOBZDtAg4v7}
    virtual-host: ${RABBITMQ_HOST:"/"}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:lEtfbOBZDtAg4v7}
    url: ${POSTGRES_URL:jdbc:postgresql://192.241.149.226:5432/db_mab}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM:http://192.241.149.226:8080/realms/mab-manitos}
          jwk-set-uri: ${KEYCLOAK_OPEN_ID:http://192.241.149.226:8080/realms/mab-manitos/protocol/openid-connect/certs}
server:
  port: ${PORT:8012}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}
token:
  converter:
    principal-attribute: preferred_username
    resource-id: backend_security_test

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER_URI:http://192.241.149.226:9411/api/v2/spans}


security-constraints:
  constraints:
    - auth-roles:
        - permitAll
      security-collections:
        - name: registroDePacientes
          patterns:
            - /api/v1/registry/patient
          methods:

    - auth-roles:
        - permitAll
      security-collections:
        - name: paisesCiudades
          patterns:
            - /api/v1/country-cities
          methods:

    - auth-roles:
        - doctorJefe
        - doctor
      security-collections:
        - name: request
          patterns:
            - /api/v1/request
            - /api/v1/request/**
          methods:

    - auth-roles:
        - doctorJefe
      security-collections:
        - name: assign
          patterns:
            - /api/v1/doctor/assign/**
          methods:

    - auth-roles:
        - doctorJefe
        - doctor
      security-collections:
        - name: doctor
          patterns:
            - /api/v1/doctor/**
          methods:

    - auth-roles:
        - doctorJefe
        - doctor
      security-collections:
        - name: cycle
          patterns:
            - /api/v1/cycle
          methods:
