POST http://192.241.149.226:8080/realms/prove/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

response_type=code&grant_type=client_credentials&client_id=backend_security_test&client_secret=7Uhgxu84CcOel16ycyItcTTZN0xnvwUY

> {%
    client.global.set("access_token", "Bearer " + response.body["access_token"]);
    client.log(client.global.get("access_token"));
%}
###